export const GET_JOBS = "GET_JOBS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY= "ADD_COMPANY";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEES";
export const PUT_EMPLOYEE = "PUT_EMPLOYEE";
export const FORM_EMPLOYEE_UPDATE = "FORM_EMPLOYEE_UPDATE";
export const ADD_JOB = "ADD_JOB";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const CLEAR_JOBS = "CLEAR_JOBS";
export const DELETE_JOB = "DELETE_JOBS";
export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const OPEN_EMPLOYEE_DETAIL_FROM = "OPEN_EMPLOYEE_DETAIL_FROM";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const OPEN_EMPLOYEE_DELETE_FROM = "OPEN_EMPLOYEE_DELETE_FROM";
export const OPEN_EMPLOYEE_CREATE_FROM = "OPEN_EMPLOYEE_CREATE_FROM";
export const GET_GENDER = "GET_GENDER";
export const GET_RELATIONSHIPSTATUS = "GET_RELATIONSHIPSTATUS";
export const CHECKBOX_CHANGE = "CHECKBOX_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const OPEN_COMPANY_CREATE_FROM = "OPEN_COMPANY_CREATE_FROM";
export const COMPANY_ID = "COMPANY_ID";
export const PUT_COMPANY = "PUT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const OPEN_COMPANY_DELETE_FROM = "OPEN_COMPANY_DELETE_FROM";
export const OPEN_COMPANY_DETAIL_FROM = "OPEN_COMPANY_DETAIL_FROM";



